alttester/AltTester-Unity-SDK

Docs/source/pages/known-issues.rst
@RobertPoienar @ReichEdvin  @robert-altom  @rucindrea @iulianatodoran
=> updated versions

Assets/AltTester/AltServer/AltMockUpPointerInputModule.cs, Assets/AltTester/AltServer/Input.cs, Assets/AltTester/Examples/Scenes/Scene 7 New Input System Actions.unity, Assets/AltTester/Examples/Test/Editor/Driver/TestForNIS.cs
=> 967-new-input-system-double-execution-for-endtouch-begintouch-keyup-and-keydown-commands

Assets/AltTester/Prefab/AltTesterPrefab.prefab, Assets/AltTester/Prefab/AltTesterPrefab.prefab.meta, Assets/Editor/CreateAltPrefab.cs
=> Old AltUnity name and version still appearing in AltTesterPrefab

Assets/AltTester/AltServer/UI/AltDialog.cs, Assets/AltTester/Examples/Test/Editor/Driver/TestForNIS.cs, Assets/AltTester/Examples/Test/Editor/Driver/Testforscene1TestSample.cs, Assets/AltTester/Prefab/AltTesterPrefab.prefab, Assets/Editor/CreateAltPrefab.cs, Docs/source/home.rst, Docs/source/index.rst, Docs/source/pages/known-issues.rst
=> Fix issue where the game is connected but the status message remains waiting for connection

Docs/README.md, README.md
=> add information in readme

Assets/AltTester/AltServer/UI/AltDialog.cs, Assets/AltTester/Prefab/AltTesterPrefab.prefab, Assets/Editor/CreateAltPrefab.cs, Docs/source/pages/advanced-usage.md, Docs/source/pages/get-started.md
@RobertPoienar @ReichEdvin @robert-altom @SandyEma9 @Dianaserb1
=> Rename Custom Input to AltTester Input

Docs/source/pages/get-started.md
In this PR the information about the Python, C#, and Java testing setup was added.
All the setup info was added to the `get-started.md` page.
Mockup: https://docs.google.com/document/d/12bzWJDvBh_Ca0pQRE66KuBJoLjhPLp48JmjpwYpuipU/edit
=> [Documentation] Insert steps for creating setup for Python tests project

Assets/AltTester/Runtime/AltDriver/AltErrors.cs, Assets/AltTester/Runtime/AltDriver/Communication/DriverWebSocketClient.cs, Assets/AltTester/Runtime/Communication/IRuntimeWebSocketClient.cs, Assets/AltTester/Runtime/Communication/LiveUpdateCommunicationHandler.cs, Assets/AltTester/Runtime/Communication/Plugins/WebSocket.jslib, Assets/AltTester/Runtime/Communication/RuntimeCommunicationHandler.cs, Assets/AltTester/Runtime/Communication/RuntimeWebSocketClient.cs, Assets/AltTester/Runtime/Communication/WebGLWebSocket.cs, Assets/AltTester/Runtime/UI/AltDialog.cs, Bindings~/java/src/main/java/com/alttester/WebsocketConnection.java, Bindings~/java/src/main/java/com/alttester/altTesterExceptions/MultipleDriversException.java, Bindings~/python/alttester/_websocket.py, Bindings~/python/tests/integration/conftest.py
This PR adds support for error message in WebGL, and adds error handling for duplicate app name.
=> Fix error handling for the websocket clients

Docs/source/pages/known-issues.rst
@ReichEdvin @iulianatodoran @MihaiCuc98 @RobertPoienar @robert-altom @SandyEma9
=> Update known issues

.github/workflows/push.yml, Docs/source/pages/commands.md, Docs/source/pages/examples.md
=> 1303-pipelines-workflow-filter-does-not-detect-change-in-docs-when-merging-into-development

Assets/AltTester/Editor/Scripts/AltEditorConfiguration.cs, Assets/AltTester/Editor/Scripts/AltTestRunner.cs, Assets/AltTester/Editor/Scripts/AltTesterEditorWindow.cs
@rucindrea @robert-altom @gomboskriszta15 @ReichEdvin @SandyEma9
=> Added assembly filter

Bindings~/dotnet/AltDriver.Tests/AltDriver.Tests.csproj
Updated `Microsoft.NET.Test.Sdk` version in `AltDriver.Tests.csproj`
=> Update `AltDriver.Tests.csproj` with a newer version for the `Microsoft.NET.Test.Sdk` package

.github/workflows/push.yml, .github/workflows/runs-at-night.yml, Assets/Examples/Test/Editor/Driver/Testforscene1TestSample.cs, Bindings~/python/requirements-dev.txt, Bindings~/python/tests/integration/conftest.py
this will fix the nighlty runs
=> Fix night run pipeline

Bindings~/robot/src/AltTesterLibrary/AltTesterKeywords.py
Please review when possible @alttester/developers.
cc: @SandyEma9
=> Duplicated keywords removal

Docs/source/conf.py, Docs/source/pages/commands.md
@alttester/developers please review when possible.
Thanks!
=> ROBOT: API doc updates - with robot examples

Docs/source/pages/get-started.md
=> [Get started] Add in Java test setup code snippets for the required alttester and JUnit dependencies

Docs/source/pages/commands.md
@alttester/developers please review when possible
Relates to https://github.com/alttester/AltTester-Unity-SDK/pull/1569 and https://github.com/orgs/alttester/projects/1/views/1?filterQuery=&pane=issue&itemId=56468808
=> Formatting issues

Bindings~/robot/tests/test_scene01.robot, Docs/source/pages/commands.md
@alttester/developers please review when possible.
Linked ticket: https://github.com/alttester/AltTester-Unity-SDK/issues/1574
=> ROBOT: Player pref key deletion test

Docs/source/pages/commands.md
@alttester/developers please review when possible.
=> ROBOT: API formatting issue

Assets/AltTester/package.json
=> Change unity version to 2020.3 in package.json

Bindings~/python/alttester/reverse_port_forwarding.py, Bindings~/robot/src/AltTesterLibrary/AltTesterKeywords.py
After #1616  is merged
@alttester/developers
=> 1614 robot remove reverse port forwarding android and remove all reverse port forwarding android not working

Docs/source/pages/commands.md
I copied the test from the repo C# tests
=> [API] [CallComponentMethod] First C# example contains command from older AltDriver version

Docs/source/pages/known-issues.rst
Added the new entry and fixed a display issue in the WebGL section
Preview with the addition and the fix
=> Add info in Known Issues about problem connecting devices with newer iOS versions in BrowserStack

Bindings~/java/src/main/java/com/alttester/Commands/FindObject/AltWaitForComponentProperty.java, Bindings~/java/src/main/java/com/alttester/Commands/FindObject/AltWaitForVisualElementProperty.java
=> Fix problem with deserialization

Assets/AltTester/Runtime/UI/AltDialog.cs
=> Fix problem with new version
